#spring.application.name=app
spring.application.name=TEST_PROPERTIES
spring.messages.basename=traducciones
spring.messages.encoding=UTF-8

logging.level.es.alumno.uned=DEBUG
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG

# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/practica
spring.datasource.username=practica
spring.datasource.password=practica
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.uploadDir=D:/UNED/DESARROLLOWEB/ped-2026/uned-aplicacionweb/imagenes/cursos/