#spring.application.name=app
spring.application.name=TEST_PROPERTIES
spring.messages.basename=traducciones
spring.messages.encoding=UTF-8

# Muestra qué método del controlador captura cada URL
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

# Muestra el flujo interno de seguridad y evaluación de @PreAuthorize
logging.level.org.springframework.security=DEBUG

logging.level.es.alumno.uned=DEBUG
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG

# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/practica
spring.datasource.username=practica
spring.datasource.password=practica
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.uploadImgDir=D:/UNED/DESARROLLOWEB/ped-2026/uned-aplicacionweb/curso/imagenes/
app.uploadDocDir=D:/UNED/DESARROLLOWEB/ped-2026/uned-aplicacionweb/curso/doc/