opcion.title=Opci�n

command.modificar=Modificar
command.buscar=Buscar

lenguaje.selector=Idioma
lenguaje.es=Español
lenguaje.en=Inglés

mensaje.nuevo=Nuevo

usuario.lista=Usuarios

usuario.admin=Admin. Usuarios
usuario.title=Usuario
usuario.email=e-mail
usuario.nombre=Nombre
usuario.role=Rol
usuario.password=Contraseña

estudiante.miperfil=Mi Perfil

login.initSession=Iniciar Sesión
login.enter=Entrar
login.register.message=¿No tienes cuenta? Regístrate
login.mensaje.error=Usuario o contraseña Incorrectos
login.mensaje.logout=Has cerrado sesión correctamente