opcion.title=Opción

command.modificar=Modificar
command.buscar=Buscar

lenguaje.selector=Idioma
lenguaje.es=Español
lenguaje.en=Inglés

mensaje.nuevo=Nuevo

usuario.lista=Usuarios

usuario.admin=Admin. Usuarios
usuario.title=Usuario
usuario.email=e-mail
usuario.nombre=Nombre
usuario.role=Rol
usuario.password=Contraseña

estudiante.miperfil=Mi Perfil

login.initSession=Iniciar Sesión
login.enter=Entrar
login.register.message=¿No tienes cuenta? Regístrate
login.mensaje.error=Usuario o contraseña Incorrectos
login.mensaje.logout=Has cerrado sesión correctamente

acceso.mensaje=Acción
acceso.fecha=F.Acceso


validations.message.nombre.mandatory=El nombre es obligatorio
validations.message.apellido1.mandatory=El primer apellido es obligatorio
validations.message.email.mandatory=El email es obligatorio
validations.message.email.validformat=Debe introducir un email válido
validations.message.password.mandatory=La contraseña es obligatoria
validations.message.password.validformat=La contraseña debe tener al menos 6 caracteres
validations.message.rol.mandatory=Rol del usuario es obligatorio
validations.message.direccion.mandatory=La dirección es obligatoria
validations.message.poblacion.mandatory=La población es obligatoria
validations.message.provincia.mandatory=La provincia es obligatoria
validations.message.codpostal.format=El código postal debe tener 5 dígitos